### ISSUE TITLE
RS Components Stock at "1"

### ISSUE THREAD

**Issue by pedroluisneves** [NexarDeveloper/nexar-supply-excel-cs#10]
Hi,

I am having an issue regarding RS stocks.
There are some references that are returning 1 as stock, but in fact does not match with Octopart website:
![image](https://user-images.githubusercontent.com/48982504/160577850-70b530ae-814a-490b-a146-9b1219fd190a.png)
![image](https://user-images.githubusercontent.com/48982504/160577924-a300c217-b817-4a28-aa0f-a75686541a69.png)

I don't know if it relates to the fact that there are 2 supply codes for the same component, and if there is a way to fix this issue.

**Comment by RobAltium** [comment]
Hi [pedroluisneves](https://github.com/pedroluisneves) - thanks for your note.  I see the same behaviour.  The Excel add-in is reflecting the API (Nexar and Octopart).  Let me chase this up and get back to you.

**Comment by pedroluisneves** [comment]
Thank you Rob.

I am also noticing that the same issue occurs on Altium:
![image](https://user-images.githubusercontent.com/48982504/160597809-b2524b12-b516-400d-809f-eaed10caad22.png)

**Comment by RobAltium** [comment]
If you try again now, do you see "300"?

**Comment by RobAltium** [comment]
I'm now seeing the 300 via the API and the Excel add-in so the inventory has updated in the past hour.  I think the discrepancy between 300 and 1,370 quoted on the Octopart.com website is due to the country.  I'm in the UK and see 1,370 components are available to ship here.  However, those in the US will only see 300 comopnents available.  The Excel add-in, along with the default Nexar and Octopart API query, will consider "US" as the default country which is why this is the result the add-in shows.  

The Excel add-in does not yet support specifying the country code.  However, this is supported in the Nexar API.  For example, run this query with and without the `country: "GB"` line and you'll see the 300 versus 1,370 inventory levels...

```
query MultiMatch {
  supMultiMatch(
    country: "GB",
    queries: [{ mpn: "AR 32 HZL-TT", limit: 10 }]
  ) {
    hits
    parts {
      mpn
      name
      sellers {
        company {
          name
        }
        country        
        offers {
          inventoryLevel
        }
      }
    }
  }
}

**Comment by pedroluisneves** [comment]
In fact, I'm now seeing the value 300, however, for many other products I still get "1".
![image](https://user-images.githubusercontent.com/48982504/160628750-6a18cebd-3cf3-43f0-a15d-00b1934b2cd4.png)

**Comment by pedroluisneves** [comment]
In fact, I'm now seeing the value 300, however, for many other products I still get "1".
![image](https://user-images.githubusercontent.com/48982504/160629197-ccf0fb76-204b-4d59-ab11-e651a60818f9.png)

**Comment by pedroluisneves** [comment]
Hi Rob, the issue still exist and sometimes it gets fix, but some other place got it.
The feedback I received seams to point for RS data source, nevertheless, let me know if you need more examples.

**Comment by RobAltium** [comment]
Yes, that's correct.  This was a data source issue, which affected the API, it's nothing to do with the Excel add-in.  So I shall close this issue.
