### ISSUE TITLE
Currency conversion : from $ to €

### ISSUE THREAD

**Issue by rsaidli** [NexarDeveloper/nexar-supply-excel-cs#11]
Hello, 

Thank you for your work.

I am trying to add your functions in my bom excel files in order to have a better picture of the stocks.
I am in France and I would like to use the EUR currency instead of the $.
When using NEXAR_SUPPLY_DISTRIBUTOR_PRICE with the last parameter set to EUR I have an error message.
I also tried GBP and it also returns an error.

Regards.

**Comment by drrobbarton** [comment]
Hi @rsaidli - thank you for your message ... and appreciation of our work!  

We'll take a look and get back to you on this soon.  Is there a particular MPN / distributor that is causing you trouble?

**Comment by RobAltium** [comment]
Hi @rsaidli - thank you for your message ... and appreciation of our work!  

We'll take a look and get back to you on this soon.  Is there a particular MPN / distributor that is causing you trouble?

**Comment by rsaidli** [comment]
Hi @RobAltium,

I tried the following distributors : 
MOUSER
Digi-Key
FARNELL
RS Components
AVNET

if I use =NEXAR_SUPPLY_DISTRIBUTOR_PRICE(A9;C9;D9;100;"USD") I got a correct price
if I use =NEXAR_SUPPLY_DISTRIBUTOR_PRICE(A9;C9;D9;100;"EUR") I got an error message : 
ERROR:   Query did not provide a result. Please widen your search criteria.

Using API / IDE I can convert prices from USD to EUR using for example : convertedPrice 

query PartSearch {
  supSearch(
    q: "LTC6090CS8E#PBF"
    country: "FR"
    currency: "EUR"
    inStockOnly: false
    limit: 1
  ) {
    hits
    results {
      part {
        mpn
        manufacturer {
          name
        }
        sellers(authorizedOnly: false) {
          company {
            name
            homepageUrl
          }
          offers {
            inventoryLevel
            moq
            prices {
              quantity
              convertedCurrency
              convertedPrice
            }
            sku
          }
        }
      }
    }
  }
}

Regards,

**Comment by RobAltium** [comment]
Hi there,
The query that the Excel add-in uses (in the latest version 0.4.0) is this `supMultiMatch` query...

```
query ExcelAddinQuery($queries: [SupPartMatchQuery!]!) {
  supMultiMatch(queries: $queries) {
    reference
    error
    hits
    parts {
      v3uid
      mpn
      manufacturer {
        id
        name
        homepageUrl
      }
      bestDatasheet {
        url
      }
      octopartUrl
      sellers {
        offers {
          id
          sku
          factoryLeadDays
          factoryPackQuantity
          inventoryLevel
          onOrderQuantity
          orderMultiple
          multipackQuantity
          packaging
          moq
          clickUrl
          updated
          prices {
            currency
            quantity
            price
          }
        }
        company {
          id
          name
          homepageUrl
        }
        isAuthorized
      }
    }
  }
```
where the query variable contains the specified MPN.

So what does this mean?

Take MPN "0603YD474KAT2A" as an example.  Running that through the above query produces a result with 24 sellers.  Within their offers you will find some in various currencies, including USD, GBP, EUR, SGP, etc...  The filter in the add-in allows a filter so as to only consider those offers in your specified currency.

Whilst the `supMultiMatch` GraphQL query does support the `country` and `currency` parameters - which I think influences the response without applying a hard currency filter - supporting these input parameters has not yet been extended into the Excel add-in.

**Comment by rsaidli** [comment]
Hi @RobAltium,

Thank you for the explanation.

I can implement a USD to EUR conversion.

Since Tuesday the login function returns : Unable to login to Nexar application, check Client id and Secret

On the dashboard : you have used 95 of 1000 queries.

Is it an issue on my side or your side ?

Regards,

dli

**Comment by RobAltium** [comment]
Hi @rsaidli,
I'm pleased you have the currency conversion working.  
Have you tried the "Refresh Login" button on the Nexar Supply ribbon?  Access tokens expire after 24 hours and this will regenerate a new one.  
Also, please ensure there is only one call to `=NEXAR_SUPPLY_LOGIN()` to avoid conflicts.

**Comment by Madeliine** [comment]
Hello,
I'd like to get the currency conversion working (same problem as @rsaidli) in the Excel add-in. I tried to add the country and the currency in the parameters of the supMultiMatch query (in the **function Nexar.Supply.Api.ApiV4.GetMultiMatchQuery in file ApiV4.cs** ),  but it doesn't seem to work. I got an error that says : **"Expected a `String`-token, but found a `Name`-token"**. However, the same query works on https://api.nexar.com/graphql/.  

For now, here is the line of code that I have changed (compared to what was done): 
`return "query($queries: [SupPartMatchQuery!]!) {supMultiMatch (queries: $queries country: \"FR\" currency: \"EUR\") { reference error hits parts { v3uid mpn shortDescription manufacturer { id name homepageUrl } "
                + bestDatasheet 
                + "octopartUrl sellers { offers { id sku " 
                + factoryLeadDays  
                + "factoryPackQuantity inventoryLevel onOrderQuantity orderMultiple multipackQuantity packaging moq clickUrl updated prices { currency quantity price } } company { id name homepageUrl } isAuthorized } } } }";`
                
Is there a way to implement this, so that it works ?
   
Regards,

**Comment by RobAltium** [comment]
Hi @Madeliine 
You may need to escape the `\` characters, so something like... 
` {supMultiMatch (queries: $queries country: \\\"FR\\\" currency: \\\"EUR\\\") {`

However, I wonder if there are other changes that are needed - in which case please report back and so we can talk to our product team about getting an enhancement on the roadmap soon.

**Comment by Madeliine** [comment]
Hi @RobAltium 
Your solution works perfectly ! Thank you very much.
I had to change some others parameters, so for people who want to make it works, I'm going to list the modifications I've done (note that I didn't need to have another currency than EUR, so in my case, it is now impossible to change the currency from Excel): 
So first of all, the query (in the function Nexar.Supply.Api.ApiV4.GetMultiMatchQuery in file ApiV4.cs ) is now: 
`"query($queries: [SupPartMatchQuery!]!) {supMultiMatch (queries: $queries country: \\\"FR\\\" currency: \\\"EUR\\\") {reference error hits parts { v3uid mpn shortDescription manufacturer { id name homepageUrl } "
                + bestDatasheet 
                + "octopartUrl sellers { offers { id sku " 
                + factoryLeadDays 
                + "factoryPackQuantity inventoryLevel onOrderQuantity orderMultiple multipackQuantity packaging moq clickUrl updated prices {convertedCurrency convertedPrice quantity } } company { id name homepageUrl } isAuthorized } } } }";`

Then, I had to change the class definition of 'Price' (in file SupplySchema.cs ) and modify the new parameters convertedPrice and convertedCurrency: 

public partial class Price
    {

       [JsonProperty("quantity")] 
        public long Quantity { get; set; }

        [JsonProperty("convertedCurrency")]
        public string ConvertedCurrency { get; set; }

       [JsonProperty("convertedPrice")]
       public double ConvertedPrice { get; set; } 
    }
And finally, every time it was written something like `Price.Currency` or `Price.PricePrice`, I wrote `Price.ConvertedCurrency` or `Price.ConvertedPrice`

I'm aware that some parts of the code are now useless (like checking the currency), but in order to avoid changing lots of things in the programm, I let it. 

So, suggested improvement : implement a way to change the convertedCurrency from Excel ;)

Have a good day,

**Comment by RobAltium** [comment]
It's been a while, so I'm closing this issue as resolved.  I'm glad you have a workable solution.
