### ISSUE TITLE
Discrepancy between actual distributor stock/price and result of the function

### ISSUE THREAD

**Issue by anasalbastami** [NexarDeveloper/nexar-supply-excel-cs#2]
Hi, thanks for supporting this great Excel tool. I am currently trying it out to see how accurate the information is, but I encountered these two issues:

1) The "NEXAR_SUPPLY_DISTRIBUTOR_PRICE" function seems to give the same price regardless of the quantity entered. After trying it out on several parts, it seems that it only picks the correct lowest price (corresponding to the highest quantity) which matches the lowest price from the distributor. I want to be able to get the price for 1x, 5x, 10x, 100x, etc. parts as per the distributor's price breakdown, but it currently gives the same result for all quantities.

2) The price and stock returned by the functions do not always match what is on the distributor's website (see Digikey price of part #: FN2010-20-07, or Mouser stock level of part #: LNC2V222MSEF for example). For the same parts, the price and stock displayed on Octopart's website exactly matches the info on the distributor's site. This suggests that the database used by the Excel add-in might not be up-to-date and might need to be verified. Is it using a different database than that of Octopart?

Hopefully these can be fixed soon!

**Comment by RobAltium** [comment]
Hi @anasalbastami and thank you very much for raising this issue.

1. There was a bug here, which has been fixed in the latest push (an hour ago).  Do feel free to try it out.

2. The Nexar Excel Add-in uses the same Octopart database.  In fact, Nexar calls the Octopart API under the hood.  Using the latest Add-in version, I did a quick search and found things seem to match for the two parts you mention now.  See image.  Octopart processes part data updates very regularly so prices and availability do change over time.  However, if you do find a case that fails for you please let me know and I'll take a look.  A better comparison is with the Octopart APIv4 and the Nexar Excel Add-in (or Nexar API).

![image](https://user-images.githubusercontent.com/75626416/131902761-9ab0edcb-1211-4035-a401-093b3e47934f.png)
