### ISSUE TITLE
Adding an isAuthorized field to NEXAR_SUPPLY_DISTRIBUTOR_STOCK() 

### ISSUE THREAD

**Issue by MJAdamczyk** [NexarDeveloper/nexar-supply-excel-cs#7]
Hi Rob,

I would like to request that the above function have a field added to it that checks to see if the stock listed is from an authorized or non-authorized distributor.  This would help me find "useful" stock with the plugin.  As it stands, I still have to manually confirm available stock with the website or with a separate GraphQL query.

**Comment by RobAltium** [comment]
Thanks @MJAdamczyk - I agree this would be a useful enhancement to the functions.  I encourage the community to "like" your comment if they would also benefit.  This will help with our internal prioritisation.  If there are specific functions, other than `NEXAR_SUPPLY_DISTRIBUTOR_STOCK()`, I encourage users to add a comment below which can also be liked to help us gauge priority.

**Comment by RobAltium** [comment]
Hi @MJAdamczyk and thanks for the idea.  I can see value in this flag and it is now implemented in the latest version, v0.4.0.

**Comment by TwoSquareInc** [comment]
Hi Rob,
I dont know what im doing wrong, but for me it doesen't work
I took a part MPN - TM4C1294NCPDTI3R in A105 which is not in stock on Authorized Dealers

I tried different arguments with the fx
=@NEXAR_SUPPLY_DISTRIBUTOR_STOCK(A105;;;"Authorized")
=@NEXAR_SUPPLY_DISTRIBUTOR_STOCK(A105;;;0)
=@NEXAR_SUPPLY_DISTRIBUTOR_STOCK(A105;;;"optional")
and so on..

it always shows me like 65k Parts on stock which are the quantities of the no Authorîzed brokers.
![image](https://user-images.githubusercontent.com/105418210/168041190-395713a9-c008-4ec3-8430-02b37ff422ba.png)

Same for the other arguments like Distributor Stock etc.

Any idea what im doing wrong?

**Comment by RobAltium** [comment]
Hi [TwoSquareInc](https://github.com/TwoSquareInc) - and thanks for your question.

Aha, I see what the issue is here.  You were close: the valid options for the "Authorized" aregument are "yes", "no" and (the default) "any".  In fact any case-insensitive word starting "Y" or "N" for the yes/no options.  So compare these two and you should see "65,159" versus "Not in stock" for the MPN you quote above...

`=@NEXAR_SUPPLY_DISTRIBUTOR_STOCK("TM4C1294NCPDTI3R",,,"Yes")`
`=@NEXAR_SUPPLY_DISTRIBUTOR_STOCK("TM4C1294NCPDTI3R",,,"No")`

**Comment by TwoSquareInc** [comment]
@RobAltium 
Thanks a lot for your fast Support! Now it works perfectly!
All the best and a good Day
